# Generated by Django 4.2.2 on 2023-06-18 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_file_downloads_file_emails_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RenameField(
            model_name='file',
            old_name='created_at',
            new_name='uploaded_at',
        ),
    ]
